import 'package:system_info2/system_info2.dart';

List<ProcessorArchitecture> supportedArchitectures = [
  ProcessorArchitecture.arm64,
  ProcessorArchitecture.arm,
  ProcessorArchitecture.x86_64
];

Map<ProcessorArchitecture, String> downloadUrls = {
  ProcessorArchitecture.arm64:
      "https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_arm64.tar.gz",
  ProcessorArchitecture.arm:
      "https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_armv7.tar.gz",
  ProcessorArchitecture.x86_64:
      "https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_amd64.tar.gz"
};

// Format:
// Voice Name: [Sample Rate, Language Code, Model URL, Model Metadata URL, Filename, Sample URL (Optional), Model card (Optional)]

Map<String, Map<String, List<String>>> voices = {
  "Arabic (Jordan)": {
    "Kareem": [
      "22050",
      "ar-jo",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ar/ar_JO/kareem/medium/ar_JO-kareem-medium.onnx.json?download=true",
      "ar_JO-kareem-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ar/ar_JO/kareem/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ar/ar_JO/kareem/medium/MODEL_CARD?download=true",
    ]
  },
  "Catalan": {
    "Ona": [
      "22050",
      "ca",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium.onnx.json?download=true",
      "ca_ES-upc_ona-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_ona/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_ona/medium/MODEL_CARD?download=true",
    ],
    "Pau": [
      "16000",
      "ca",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_pau/x_low/ca_ES-upc_pau-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_pau/x_low/ca_ES-upc_pau-x_low.onnx.json?download=true",
      "ca-upc_pau-x-low.onnx",
      "https://github.com/rhasspy/piper-samples/raw/master/samples/ca/ca_ES/upc_pau/x_low/speaker_0.mp3",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ca/ca_ES/upc_pau/x_low/MODEL_CARD?download=true",
    ],
  },
  "Czech": {
    "Jirka": [
      "22050",
      "cs-cz",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/cs/cs_CZ/jirka/medium/cs_CZ-jirka-medium.onnx.json?download=true",
      "cs_CZ-jirka-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/cs/cs_CZ/jirka/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/cs/cs_CZ/jirka/medium/MODEL_CARD?download=true",
    ],
  },
  "Danish": {
    "Talesyntese": [
      "22050",
      "da",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/da/da_DK/talesyntese/medium/da_DK-talesyntese-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/da/da_DK/talesyntese/medium/da_DK-talesyntese-medium.onnx.json?download=true",
      "da-nst_talesyntese-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/da/da_DK/talesyntese/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/da/da_DK/talesyntese/medium/MODEL_CARD?download=true",
    ]
  },
  "German": {
    "Eva": [
      "16000",
      "de",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/eva_k/x_low/de_DE-eva_k-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/eva_k/x_low/de_DE-eva_k-x_low.onnx.json?download=true",
      "de-eva_k-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/eva_k/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/eva_k/x_low/MODEL_CARD?download=true",
    ],
    "Karlsson": [
      "16000",
      "de",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/karlsson/low/de_DE-karlsson-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/karlsson/low/de_DE-karlsson-low.onnx.json?download=true",
      "de-karlsson-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/karlsson/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/karlsson/low/MODEL_CARD?download=true",
    ],
    "Kerstin": [
      "16000",
      "de",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/kerstin/low/de_DE-kerstin-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/kerstin/low/de_DE-kerstin-low.onnx.json?download=true",
      "de-kerstin-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/kerstin/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/kerstin/low/MODEL_CARD?download=true",
    ],
    "Pavoque": [
      "16000",
      "de",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/pavoque/low/de_DE-pavoque-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/pavoque/low/de_DE-pavoque-low.onnx.json?download=true",
      "de-pavoque-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/pavoque/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/pavoque/low/MODEL_CARD?download=true",
    ],
    "Ramona": [
      "16000",
      "de",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/ramona/low/de_DE-ramona-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/ramona/low/de_DE-ramona-low.onnx.json?download=true",
      "de-ramona-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/ramona/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/ramona/low/MODEL_CARD?download=true",
    ],
    "Thorsten": [
      "22050",
      "de",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/high/de_DE-thorsten-high.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/high/de_DE-thorsten-high.onnx.json?download=true",
      "de_DE-thorsten-high.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/high/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/de/de_DE/thorsten/high/MODEL_CARD?download=true",
    ],
  },
  "Greek": {
    "Repunzelina": [
      "16000",
      "el-gr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/el/el_GR/rapunzelina/low/el_GR-rapunzelina-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/el/el_GR/rapunzelina/low/el_GR-rapunzelina-low.onnx.json?download=true",
      "el-gr-rapunzelina-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/el/el_GR/rapunzelina/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/el/el_GR/rapunzelina/low/MODEL_CARD?download=true",
    ]
  },
  "English (UK)": {
    "Alan": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx.json?download=true",
      "en_GB-alan-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/samples/speaker_0.mp3?download=true1",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/MODEL_CARD?download=true",
    ],
    "Alba": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/en_GB-alba-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/en_GB-alba-medium.onnx.json?download=true",
      "en_GB-alba-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_GB/alba/medium/MODEL_CARD?download=true",
    ],
    "Aru": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/aru/medium/en_GB-aru-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/aru/medium/en_GB-aru-medium.onnx.json?download=true",
      "en_GB-aru-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/aru/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/aru/medium/MODEL_CARD?download=true",
    ],
    "Jenny (Dioco)": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx.json?download=true",
      "en_GB-jenny_dioco-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/jenny_dioco/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/jenny_dioco/medium/MODEL_CARD?download=true",
    ],
    "Northern English Male": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json?download=true",
      "en_GB-northern_english_male-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/northern_english_male/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/northern_english_male/medium/MODEL_CARD?download=true",
    ],
    "Semaine": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx.json?download=true",
      "en_GB-semaine-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/semaine/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/semaine/medium/MODEL_CARD?download=true",
    ],
    "Southern English Female": [
      "16000",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx.json?download=true",
      "en-gb-southern_english_female-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/low/MODEL_CARD?download=true",
    ],
    "VCTK": [
      "22050",
      "en-gb",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx.json?download=true",
      "en_GB-vctk-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/vctk/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/vctk/medium/MODEL_CARD?download=true",
    ]
  },
  "English (US)": {
    "Amy": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json?download=true",
      "en_US-amy-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/MODEL_CARD?download=true",
    ],
    "Arctic": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/arctic/medium/en_US-arctic-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/arctic/medium/en_US-arctic-medium.onnx.json?download=true",
      "en_US-arctic-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/arctic/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/arctic/medium/MODEL_CARD?download=true",
    ],
    "Danny": [
      "16000",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/danny/low/en_US-danny-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/danny/low/en_US-danny-low.onnx.json?download=true",
      "en_US-danny-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/danny/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/danny/low/MODEL_CARD?download=true",
    ],
    "HFC Female": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx.json?download=true",
      "en_US-hfc_female-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/MODEL_CARD?download=true",
    ],
    "HFC Male": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx.json?download=true",
      "en_US-hfc_male-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/MODEL_CARD?download=true",
    ],
    "Joe": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/joe/medium/en_US-joe-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/joe/medium/en_US-joe-medium.onnx.json?download=true",
      "en_US-joe-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/joe/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/joe/medium/MODEL_CARD?download=true",
    ],
    "Kathleen": [
      "16000",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kathleen/low/en_US-kathleen-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kathleen/low/en_US-kathleen-low.onnx.json?download=true",
      "en-us-kathleen-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kathleen/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kathleen/low/MODEL_CARD?download=true",
    ],
    "Kusal": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kusal/medium/en_US-kusal-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kusal/medium/en_US-kusal-medium.onnx.json?download=true",
      "en_US-kusal-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kusal/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kusal/medium/MODEL_CARD?download=true",
    ],
    "L2 Arctic": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx.json?download=true",
      "en_US-l2arctic-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/l2arctic/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/l2arctic/medium/MODEL_CARD?download=true",
    ],
    "Lessac": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/high/en_US-lessac-high.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/high/en_US-lessac-high.onnx.json?download=true",
      "en_US-lessac-high.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/high/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/high/MODEL_CARD?download=true",
    ],
    "Libritts": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx.json?download=true",
      "en_US-libritts-high.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/MODEL_CARD?download=true",
    ],
    "Libritts R": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json?download=true",
      "en_US-libritts_r-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/MODEL_CARD?download=true",
    ],
    "Ryan": [
      "22050",
      "en-us",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/high/en_US-ryan-high.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/high/en_US-ryan-high.onnx.json?download=true",
      "en_US-ryan-high.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/high/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/high/MODEL_CARD?download=true",
    ],
  },
  "Spanish (Spain)": {
    "Carl": [
      "16000",
      "es",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/carlfm/x_low/es_ES-carlfm-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/carlfm/x_low/es_ES-carlfm-x_low.onnx.json?download=true",
      "es-carlfm-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/carlfm/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/carlfm/x_low/MODEL_CARD?download=true",
    ],
    "Dave FX": [
      "22050",
      "es",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/es_ES-davefx-medium.onnx.json?download=true",
      "es_ES-davefx-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/davefx/medium/MODEL_CARD?download=true",
    ],
    "MLS 10246": [
      "16000",
      "es",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_10246/low/es_ES-mls_10246-low.onnx.json?download=true",
      "es-mls_10246-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_10246/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_10246/low/MODEL_CARD?download=true",
    ],
    "MLS 9972": [
      "16000",
      "es",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_9972/low/es_ES-mls_9972-low.onnx.json?download=true",
      "es-mls_9972-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_9972/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/mls_9972/low/MODEL_CARD?download=true",
    ],
    "Sharvard": [
      "22050",
      "es",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/sharvard/medium/es_ES-sharvard-medium.onnx.json?download=true",
      "es_ES-sharvard-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/sharvard/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_ES/sharvard/medium/MODEL_CARD?download=true",
    ]
  },
  "Spanish (Mexico)": {
    "Ald": [
      "22050",
      "es-mx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/ald/medium/es_MX-ald-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/ald/medium/es_MX-ald-medium.onnx.json?download=true",
      "es_MX-ald-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/ald/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/ald/medium/MODEL_CARD?download=true",
    ]
  },
  "Finnish": {
    "Harri": [
      "22050",
      "fi",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium/fi_FI-harri-medium.onnx.json?download=true",
      "fi_FI-harri-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fi/fi_FI/harri/medium/MODEL_CARD?download=true",
    ]
  },
  "French": {
    "Gilles": [
      "16000",
      "fr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/gilles/low/fr_FR-gilles-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/gilles/low/fr_FR-gilles-low.onnx.json?download=true",
      "fr-gilles-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/gilles/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/gilles/low/MODEL_CARD?download=true",
    ],
    "MLS 1840": [
      "16000",
      "fr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/mls_1840/low/fr_FR-mls_1840-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/mls_1840/low/fr_FR-mls_1840-low.onnx.json?download=true",
      "fr-mls_1840-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/mls_1840/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/mls_1840/low/MODEL_CARD?download=true",
    ],
    "Siwis": [
      "22050",
      "fr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/fr_FR-siwis-medium.onnx.json?download=true",
      "fr-siwis-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/siwis/medium/MODEL_CARD?download=true",
    ],
    "UPMC": [
      "22050",
      "fr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/upmc/medium/fr_FR-upmc-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/upmc/medium/fr_FR-upmc-medium.onnx.json?download=true",
      "fr_FR-upmc-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/upmc/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/fr/fr_FR/upmc/medium/MODEL_CARD?download=true",
    ]
  },
  "Hungarian": {
    "Anna": [
      "22050",
      "hu",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/anna/medium/hu_HU-anna-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/anna/medium/hu_HU-anna-medium.onnx.json?download=true",
      "hu_HU-anna-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/anna/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/anna/medium/MODEL_CARD?download=true",
    ],
    "Berta": [
      "22050",
      "hu",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/berta/medium/hu_HU-berta-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/berta/medium/hu_HU-berta-medium.onnx.json?download=true",
      "hu_HU-berta-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/berta/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/berta/medium/MODEL_CARD?download=true",
    ],
    "Imre": [
      "22050",
      "hu",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/imre/medium/hu_HU-imre-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/imre/medium/hu_HU-imre-medium.onnx.json?download=true",
      "hu_HU-imre-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/imre/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/hu/hu_HU/imre/medium/MODEL_CARD?download=true",
    ]
  },
  "Icelandic": {
    "Bui": [
      "22050",
      "is",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/bui/medium/is_IS-bui-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/bui/medium/is_IS-bui-medium.onnx.json?download=true",
      "is-bui-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/bui/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/bui/medium/MODEL_CARD?download=true",
    ],
    "Salka": [
      "22050",
      "is",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/salka/medium/is_IS-salka-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/salka/medium/is_IS-salka-medium.onnx.json?download=true",
      "is-salka-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/salka/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/salka/medium/MODEL_CARD?download=true",
    ],
    "Steinn": [
      "22050",
      "is",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/steinn/medium/is_IS-steinn-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/steinn/medium/is_IS-steinn-medium.onnx.json?download=true",
      "is-steinn-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/steinn/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/steinn/medium/MODEL_CARD?download=true",
    ],
    "Ugla": [
      "22050",
      "is",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/ugla/medium/is_IS-ugla-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/ugla/medium/is_IS-ugla-medium.onnx.json?download=true",
      "is-ugla-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/ugla/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/is/is_IS/ugla/medium/MODEL_CARD?download=true",
    ],
  },
  "Italian": {
    "Riccardo": [
      "16000",
      "it",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/riccardo/x_low/it_IT-riccardo-x_low.onnx.json?download=true",
      "it-riccardo_fasol-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/riccardo/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/it/it_IT/riccardo/x_low/MODEL_CARD?download=true",
    ],
  },
  "Georgian": {
    "Natia": [
      "22050",
      "ka",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ka/ka_GE/natia/medium/ka_GE-natia-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ka/ka_GE/natia/medium/ka_GE-natia-medium.onnx.json?download=true",
      "ka_GE-natia-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ka/ka_GE/natia/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ka/ka_GE/natia/medium/MODEL_CARD?download=true",
    ]
  },
  "Kazakh": {
    "Iseke": [
      "16000",
      "kk",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/iseke/x_low/kk_KZ-iseke-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/iseke/x_low/kk_KZ-iseke-x_low.onnx.json?download=true",
      "kk-iseke-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/iseke/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/iseke/x_low/MODEL_CARD?download=true",
    ],
    "Issai": [
      "22050",
      "kk",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/issai/high/kk_KZ-issai-high.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/issai/high/kk_KZ-issai-high.onnx.json?download=true",
      "kk-issai-high.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/issai/high/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/issai/high/MODEL_CARD?download=true",
    ],
    "Raya": [
      "16000",
      "kk",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/raya/x_low/kk_KZ-raya-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/raya/x_low/kk_KZ-raya-x_low.onnx.json?download=true",
      "kk-raya-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/raya/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/kk/kk_KZ/raya/x_low/MODEL_CARD?download=true",
    ],
  },
  "Luxembourgish": {
    "Marylux": [
      "22050",
      "lu",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/lb/lb_LU/marylux/medium/lb_LU-marylux-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/lb/lb_LU/marylux/medium/lb_LU-marylux-medium.onnx.json?download=true",
      "lb_LU-marylux-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/lb/lb_LU/marylux/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/lb/lb_LU/marylux/medium/MODEL_CARD?download=true",
    ],
  },
  "Nepali": {
    "Google": [
      "22050",
      "ne",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ne/ne_NP/google/medium/ne_NP-google-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ne/ne_NP/google/medium/ne_NP-google-medium.onnx.json?download=true",
      "ne-google-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ne/ne_NP/google/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ne/ne_NP/google/medium/MODEL_CARD?download=true",
    ],
  },
  "Dutch (Netherlands)": {
    "MLS 5809": [
      "16000",
      "nl-nl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_5809/low/nl_NL-mls_5809-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_5809/low/nl_NL-mls_5809-low.onnx.json?download=true",
      "nl-mls_5809-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_5809/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_5809/low/MODEL_CARD?download=true",
    ],
    "MLS 7432": [
      "16000",
      "nl-nl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_7432/low/nl_NL-mls_7432-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_7432/low/nl_NL-mls_7432-low.onnx.json?download=true",
      "nl-mls_7432-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_7432/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_NL/mls_7432/low/MODEL_CARD?download=true",
    ],
  },
  "Dutch (Belgium)": {
    "Nathalie": [
      "22050",
      "nl-be",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/nathalie/medium/nl_BE-nathalie-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/nathalie/medium/nl_BE-nathalie-medium.onnx.json?download=true",
      "nl_BE-nathalie-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/nathalie/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/nathalie/medium/MODEL_CARD?download=true"
    ],
    "RDH": [
      "22050",
      "nl-be",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/rdh/medium/nl_BE-rdh-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/rdh/medium/nl_BE-rdh-medium.onnx.json?download=true",
      "nl-rdh-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/rdh/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/nl/nl_BE/rdh/medium/MODEL_CARD?download=true"
    ],
  },
  "Norwegian": {
    "Talesyntese": [
      "22050",
      "no",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/no/no_NO/talesyntese/medium/no_NO-talesyntese-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/no/no_NO/talesyntese/medium/no_NO-talesyntese-medium.onnx.json?download=true",
      "no-talesyntese-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/no/no_NO/talesyntese/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/no/no_NO/talesyntese/medium/MODEL_CARD?download=true",
    ],
  },
  "Polish": {
    "Darkman": [
      "22050",
      "pl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/pl_PL-darkman-medium.onnx.json?download=true",
      "pl_PL-darkman-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/darkman/medium/MODEL_CARD?download=true",
    ],
    "Gosia": [
      "22050",
      "pl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/gosia/medium/pl_PL-gosia-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/gosia/medium/pl_PL-gosia-medium.onnx.json?download=true",
      "pl_PL-gosia-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/gosia/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/gosia/medium/MODEL_CARD?download=true",
    ],
    "MC Speech": [
      "22050",
      "pl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mc_speech/medium/pl_PL-mc_speech-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mc_speech/medium/pl_PL-mc_speech-medium.onnx.json?download=true",
      "pl_PL-mc_speech-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mc_speech/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mc_speech/medium/MODEL_CARD?download=true"
    ],
    "MLS 6892": [
      "16000",
      "pl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mls_6892/low/pl_PL-mls_6892-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mls_6892/low/pl_PL-mls_6892-low.onnx.json?download=true",
      "pl-mls_6892-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mls_6892/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pl/pl_PL/mls_6892/low/MODEL_CARD?download=true",
    ],
  },
  "Brazilian Portuguese": {
    "Edresson": [
      "16000",
      "pt-br",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/edresson/low/pt_BR-edresson-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/edresson/low/pt_BR-edresson-low.onnx.json?download=true",
      "pt-br-edresson-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/edresson/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/edresson/low/MODEL_CARD?download=true",
    ],
    "Faber": [
      "22050",
      "pt-br",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/pt_BR-faber-medium.onnx.json?download=true",
      "pt_BR-faber-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_BR/faber/medium/MODEL_CARD?download=true",
    ],
  },
  "Portuguese": {
    "Tugão": [
      "22050",
      "pt-pt",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_PT/tug%C3%A3o/medium/pt_PT-tug%C3%A3o-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_PT/tug%C3%A3o/medium/pt_PT-tug%C3%A3o-medium.onnx.json?download=true",
      "pt_PT-tugao-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_PT/tug%C3%A3o/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/pt/pt_PT/tug%C3%A3o/medium/MODEL_CARD?download=true",
    ]
  },
  "Romanian": {
    "Mihai": [
      "22050",
      "ro",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ro/ro_RO/mihai/medium/ro_RO-mihai-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ro/ro_RO/mihai/medium/ro_RO-mihai-medium.onnx.json?download=true",
      "ro_RO-mihai-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ro/ro_RO/mihai/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ro/ro_RO/mihai/medium/MODEL_CARD?download=true",
    ],
  },
  "Russian": {
    "Denis": [
      "22050",
      "ru",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/denis/medium/ru_RU-denis-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/denis/medium/ru_RU-denis-medium.onnx.json?download=true",
      "ru_RU-denis-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/denis/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/denis/medium/MODEL_CARD?download=true",
    ],
    "Dmitri": [
      "22050",
      "ru",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/dmitri/medium/ru_RU-dmitri-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/dmitri/medium/ru_RU-dmitri-medium.onnx.json?download=true",
      "ru_RU-dmitri-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/dmitri/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/dmitri/medium/MODEL_CARD?download=true",
    ],
    "Irinia": [
      "22050",
      "ru",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/irina/medium/ru_RU-irina-medium.onnx.json?download=true",
      "ru-irinia-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/irina/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/irina/medium/MODEL_CARD?download=true",
    ],
    "Ruslan": [
      "22050",
      "ru",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/ruslan/medium/ru_RU-ruslan-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/ruslan/medium/ru_RU-ruslan-medium.onnx.json?download=true",
      "ru_RU-ruslan-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/ruslan/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/ru/ru_RU/ruslan/medium/MODEL_CARD?download=true",
    ],
  },
  "Slovakian": {
    "Lili": [
      "22050",
      "sk",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sk/sk_SK/lili/medium/sk_SK-lili-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sk/sk_SK/lili/medium/sk_SK-lili-medium.onnx.json?download=true",
      "sk_SK-lili-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sk/sk_SK/lili/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sk/sk_SK/lili/medium/MODEL_CARD?download=true",
    ],
  },
  "Slovenian": {
    "Artur": [
      "22050",
      "sl",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sl/sl_SI/artur/medium/sl_SI-artur-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sl/sl_SI/artur/medium/sl_SI-artur-medium.onnx.json?download=true",
      "sl_SI-artur-medium.onnx",
      "",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sl/sl_SI/artur/medium/MODEL_CARD?download=true",
    ],
  },
  "Serbian": {
    "Serbski Institut": [
      "22050",
      "sr-rs",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sr/sr_RS/serbski_institut/medium/sr_RS-serbski_institut-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sr/sr_RS/serbski_institut/medium/sr_RS-serbski_institut-medium.onnx.json?download=true",
      "sr_RS-serbski_institut-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sr/sr_RS/serbski_institut/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sr/sr_RS/serbski_institut/medium/MODEL_CARD?download=true",
    ],
  },
  "Swedish": {
    "NST": [
      "22050",
      "sv-se",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/sv_SE-nst-medium.onnx.json?download=true",
      "sv-se-nst-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sv/sv_SE/nst/medium/MODEL_CARD?download=true",
    ],
  },
  "Swahili": {
    "Lanfrica": [
      "22050",
      "sw-cd",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sw/sw_CD/lanfrica/medium/sw_CD-lanfrica-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sw/sw_CD/lanfrica/medium/sw_CD-lanfrica-medium.onnx.json?download=true",
      "sw_CD-lanfrica-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sw/sw_CD/lanfrica/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/sw/sw_CD/lanfrica/medium/MODEL_CARD?download=true",
    ],
  },
  "Turkish": {
    "Dfki": [
      "22050",
      "tr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/tr_TR-dfki-medium.onnx.json?download=true",
      "tr_TR-dfki-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/dfki/medium/MODEL_CARD?download=true",
    ],
    "Fahrettin": [
      "22050",
      "tr",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/fahrettin/medium/tr_TR-fahrettin-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/fahrettin/medium/tr_TR-fahrettin-medium.onnx.json?download=true",
      "tr_TR-fahrettin-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/fahrettin/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/tr/tr_TR/fahrettin/medium/MODEL_CARD?download=true",
    ],
  },
  "Ukrainian": {
    "Lada": [
      "16000",
      "uk",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/lada/x_low/uk_UA-lada-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/lada/x_low/uk_UA-lada-x_low.onnx.json?download=true",
      "uk-lada-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/lada/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/lada/x_low/MODEL_CARD?download=true",
    ],
    "Ukranian TTS": [
      "22050",
      "uk",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian_tts/medium/uk_UA-ukrainian_tts-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian_tts/medium/uk_UA-ukrainian_tts-medium.onnx.json?download=true",
      "uk_UA-ukrainian_tts-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian_tts/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/uk/uk_UA/ukrainian_tts/medium/MODEL_CARD?download=true"
    ],
  },
  "Vietnamese": {
    "25 Hours": [
      "16000",
      "vi",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/25hours_single/low/vi_VN-25hours_single-low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/25hours_single/low/vi_VN-25hours_single-low.onnx.json?download=true",
      "vi-25hours-single-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/25hours_single/low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/25hours_single/low/MODEL_CARD?download=true",
    ],
    "Vais 1000": [
      "22050",
      "vi",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vais1000/medium/vi_VN-vais1000-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vais1000/medium/vi_VN-vais1000-medium.onnx.json?download=true",
      "vi_VN-vais1000-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vais1000/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vais1000/medium/MODEL_CARD?download=true",
    ],
    "Vivos": [
      "16000",
      "vi",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vivos/x_low/vi_VN-vivos-x_low.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vivos/x_low/vi_VN-vivos-x_low.onnx.json?download=true",
      "vi-vivos-x-low.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vivos/x_low/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/vi/vi_VN/vivos/x_low/MODEL_CARD?download=true",
    ],
  },
  "Chinese": {
    "Huayan": [
      "22050",
      "zh-cn",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/zh/zh_CN/huayan/medium/zh_CN-huayan-medium.onnx.json?download=true",
      "zh_CN-huayan-medium.onnx",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/zh/zh_CN/huayan/medium/samples/speaker_0.mp3?download=true",
      "https://huggingface.co/rhasspy/piper-voices/resolve/main/zh/zh_CN/huayan/medium/MODEL_CARD?download=true"
    ],
  },
};

Map<String, String> languageCodes = {
  "ar-jo": "Arabic (Jordan)",
  "ca": "Catalan",
  "cs-cz": "Czech",
  "de": "German",
  "el-gr": "Greek",
  "en-gb": "English (UK)",
  "en-us": "English (US)",
  "es": "Spanish (Spain)",
  "es-mx": "Spanish (Mexico)",
  "fi": "Finnish",
  "fr": "French",
  "hu": "Hungarian",
  "is": "Icelandic",
  "it": "Italian",
  "ka": "Georgian",
  "kk": "Kazakh",
  "lu": "Luxembourgish",
  "ne": "Nepali",
  "nl-be": "Dutch (Belgium)",
  "nl-nl": "Dutch (Netherlands)",
  "no": "Norwegian",
  "pl": "Polish",
  "pt-br": "Brazilian Portuguese",
  "pt-pt": "Portuguese",
  "ro": "Romanian",
  "ru": "Russian",
  "sk": "Slovakian",
  "sl": "Slovenian",
  "sr-rs": "Serbian",
  "sv-se": "Swedish",
  "sw-cd": "Swahili",
  "tr": "Turkish",
  "uk": "Ukrainian",
  "vi": "Vietnamese",
  "zh-cn": "Chinese"
};
