const String modelTemplate = """
GenericExecuteSynth "echo \\'\$DATA\\' | PIPER_PATH --model MODEL_PATH --output_raw | \$PLAY_COMMAND --raw --channels 1 --rate SAMPLE_RATE"
AddVoice "LANGUAGE" "MALE1" "Piper"
""";

const String sdConfigTemplate = """
###
### THIS CONFIG WAS GENERATED BY PIED
###

SymbolsPreproc "char"
SymbolsPreprocFile "gender-neutral.dic"
SymbolsPreprocFile "font-variants.dic"
SymbolsPreprocFile "symbols.dic"
SymbolsPreprocFile "emojis.dic"
SymbolsPreprocFile "orca.dic"
SymbolsPreprocFile "orca-chars.dic"
AddModule "piper" "sd_generic" "piper.conf"
DefaultModule "piper"
Include "clients/*.conf"
""";
