name: pied
base: core22
version: '0.1'
summary: Pied makes it simple to install and manage text-to-speech voices.
description: |
  Pied installs and configures the Piper neural text-to-speech engine to
  work with Speech Dispatcher. It can then be used to download and manage
  different voices.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  pied:
    command: pied

parts:
  pied:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages: [pkg-config, libgtk-3-dev]
    override-pull: |
      set -eux
      rm -rf $SNAPCRAFT_PROJECT_DIR/build
      snapcraftctl pull
