name: pied
base: core22
version: '0.1.10'
summary: Pied makes it simple to install and manage text-to-speech voices.
description: |
  Pied installs and configures the Piper neural text-to-speech engine to
  work with Speech Dispatcher. It can then be used to download and manage
  different voices.

grade: stable
confinement: strict

apps:
  pied:
    command: pied
    extensions: [gnome]
    plugs:
      - dot-config-speech-dispatcher
      - process-control
      - network
      - network-status
      - audio-playback
plugs:
  dot-config-speech-dispatcher:
    interface: personal-files
    read:
      - $HOME/.config/speech-dispatcher
      - $HOME/.config/speech-dispatcher.orig
    write:
      - $HOME/.config/speech-dispatcher
      - $HOME/.config/speech-dispatcher.orig

parts:
  pied:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages: [curl, libgstreamer1.0-dev, libgstreamer-plugins-base1.0-dev, libgstreamer-plugins-good1.0-dev]
    stage-packages: [psmisc, libaudio2, libsndio7.0, libgstreamer1.0-0, libgstreamer-plugins-base1.0-0, libgstreamer-plugins-good1.0-0, libgstreamer-plugins-bad1.0-0]
    override-pull: |
      set -eux
      rm -rf $SNAPCRAFT_PROJECT_DIR/build
      snapcraftctl pull
    build-attributes:
      - enable-patchelf

